{% set name = "SLiM" %}
{% set version = "5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MesserLab/SLiM/archive/v{{ version }}.tar.gz
  sha256: 8a5ed1f30a434730fee1446fae554523051d8429532a51946a7a1da812e52b4a

build:
  number: 0

requirements:
  build:
    - make  # [not win]
    - m2-make  # [win]
    - cmake
    - {{ compiler('c') }}  # [not win]
    - {{ stdlib("c") }}    # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    # Uses stdlibc; see https://conda-forge.org/news/2024/03/24/stdlib-migration/
    - {{ stdlib("c") }}
    # Full posix environment.
    - m2-base  # [win]

test:
  commands:
    - slim -testSLiM
    - slim -testEidos
    - eidos -testEidos

about:
  home: http://messerlab.org/slim/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Forward-time population genetics simulator

  description: |
    SLiM is an evolutionary simulation framework that combines a powerful engine
    for population genetic simulations with the capability of modeling
    arbitrarily complex evolutionary scenarios.
  doc_url: https://messerlab.org/slim/
  dev_url: https://github.com/MesserLab/SLiM

extra:
  recipe-maintainers:
    - jeromekelleher
    - bhaller
    - petrelharp
